from pathlib import Path
import sgffp

files = [
    {
        "file": "pMOZ4526.dna",
        "expected": [
            {
                "node": 3,
                "sequence": "NNNNtttGGATCCGAATTCAAGCTTCTGCAGTCTAGACTCGAGCCCGGGGATATCTACAACGTCGTGACTGGGAAAACTCCTTACGGGACTTTCCTACTTCACCAAACGTGGCTTGCCAGCCCTTACggcctcgtgatacgcctatttttataggttaatgtcatgataataatggtttcttagacgtcaggtggcacttttcggggaaatgtgcgcggaacccctatttgtttatttttctaaatacattcaaatatgtatccgctcatgagacaataaccctgataaatgcttcaataatattgaaaaaggaagagtatgcgctcacgcaactggtccagaaccttgaccgaacgcagcggtggtaacggcgcagtggcggttttcatggcttgttatgactgtttttttggggtacagtctatgcctcgggcatccaagcagcaagcgcgttacgccgtgggtcgatgtttgatgttatggagcagcaacgatgttacgcagcagggcagtcgccctaaaacaaagttaaacatcatgagggaagcggtgatcgccgaagtatcgactcaactatcagaggtagttggcgtcatcgagcgccatctcgaaccgacgttgctggccgtacatttgtacggctccgcagtggatggcggcctgaagccacacagcgatattgatttgctggttacggtgaccgtaaggcttgatgaaacaacgcggcgagctttgatcaacgaccttttggaaacttcggcttcccctggagagagcgagattctccgcgctgtagaagtcaccattgttgtgcacgacgacatcattccgtggcgttatccagctaagcgcgaactgcaatttggagaatggcagcgcaatgacattcttgcaggtatcttcgagccagccacgatcgacattgatctggctatcttgctgacaaaagcaagagaacatagcgttgccttggtaggtccagcggcggaggaactctttgatccggttcctgaacaggatctatttgaggcgctaaatgaaaccttaacgctatggaactcgccgcccgactgggctggcgatgagcgaaatgtagtgcttacgttgtcccgcatttggtacagcgcagtaaccggcaaaatcgcgccgaaggatgtcgctgccgactgggcaatggagcgcctgccggcccagtatcagcccgtcatacttgaagctagacaggcttatcttggacaagaagaagatcgcttggcctcgcgcgcagatcagttggaagaatttgtccattacgtaaaaggcgagatcaccaaggtagtcggcaaataactgtcagaccaagtttactcatatatactttagattgatttaaaacttcatttttaatttaaaaggatctaggtgaagatcctttttgataatctcatgaccaaaatcccttaacgtgagttttcgttccactgagcgtcagaccccgtagaaaagatcaaaggatcttcttgagatcctttttttctgcgcgtaatctgctgcttgcaaacaaaaaaaccaccgctaccagcggtggtttgtttgccggatcaagagctaccaactctttttccgaaggtaactggcttcagcagagcgcagataccaaatactgtccttctagtgtagccgtagttaggccaccacttcaagaactctgtagcaccgcctacatacctcgctctgctaatcctgttaccagtggctgctgccagtggcgataagtcgtgtcttaccgggttggactcaagacgatagttaccggataaggcgcagcggtcgggctgaacggggggttcgtgcacacagcccagcttggagcgaacgacctacaccgaactgagatacctacagcgtgagctatgagaaagcgccacgcttcccgaagggagaaaggcggacaggtatccggtaagcggcagggtcggaacaggagagcgcacgagggagcttccagggggaaacgcctggtatctttatagtcctgtcgggtttcgccacctctgacttgagcgtcgatttttgtgatgctcgtcaggggggcggagcctatggaaaaacgccagcaacgcggcctttttacggttcctggccttttgctggccttttgctcacatgttctttcctgcgttatcccctgattctgtggataaccgtattaccgcctttgagtgagctgataccgctcgccgcagccgaacgaccgagcgcagcgagtcagtgagcgaggaagcggaagagcgcccaatacgcaaaccgcctctccccgcgcgttggccgattcattaACTACAGGAAACAGCTATGACTCGCAAATGGGCGGTAGGCGTGTATGCCATAGCATTTTTATCCGAATTCGGATCCCTGCAGAAGCTTCTCGAGTCTAGAGATATCCCCGGGaaaNNNNGGTCTCTGGAGcacatttttaatcagcttatctcatttataaacgaaattgtataaaaatatacatgatgaactgaatagaacaatattgatctgatattctcatattgtataagaggatagactttcagacgcggagaatctgtaggaggggaccattcagagtgcctccaattttggtgttgttcattgtaccattgcaaatataaacgaagcatgcatgcttatgtatgaggtgtaacaaaattggaaacaatagccatgcaaggtgaagaatgtcacaaactcagcaacccttattcattgacgtgtccctcagtcactctcctctcatacctataaatcaccactcctcatgttctttccaattTACTAGAGACC",
            },
            {
                "node": 6,
                "sequence": "NNNNtttGGATCCGAATTCAAGCTTCTGCAGTCTAGACTCGAGCCCGGGGATATCTACAACGTCGTGACTGGGAAAACTCCTTACGGGACTTTCCTACTTCACCAAACGTGGCTTGCCAGCCCTTACggcctcgtgatacgcctatttttataggttaatgtcatgataataatggtttcttagacgtcaggtggcacttttcggggaaatgtgcgcggaacccctatttgtttatttttctaaatacattcaaatatgtatccgctcatgagacaataaccctgataaatgcttcaataatattgaaaaaggaagagtatgcgctcacgcaactggtccagaaccttgaccgaacgcagcggtggtaacggcgcagtggcggttttcatggcttgttatgactgtttttttggggtacagtctatgcctcgggcatccaagcagcaagcgcgttacgccgtgggtcgatgtttgatgttatggagcagcaacgatgttacgcagcagggcagtcgccctaaaacaaagttaaacatcatgagggaagcggtgatcgccgaagtatcgactcaactatcagaggtagttggcgtcatcgagcgccatctcgaaccgacgttgctggccgtacatttgtacggctccgcagtggatggcggcctgaagccacacagcgatattgatttgctggttacggtgaccgtaaggcttgatgaaacaacgcggcgagctttgatcaacgaccttttggaaacttcggcttcccctggagagagcgagattctccgcgctgtagaagtcaccattgttgtgcacgacgacatcattccgtggcgttatccagctaagcgcgaactgcaatttggagaatggcagcgcaatgacattcttgcaggtatcttcgagccagccacgatcgacattgatctggctatcttgctgacaaaagcaagagaacatagcgttgccttggtaggtccagcggcggaggaactctttgatccggttcctgaacaggatctatttgaggcgctaaatgaaaccttaacgctatggaactcgccgcccgactgggctggcgatgagcgaaatgtagtgcttacgttgtcccgcatttggtacagcgcagtaaccggcaaaatcgcgccgaaggatgtcgctgccgactgggcaatggagcgcctgccggcccagtatcagcccgtcatacttgaagctagacaggcttatcttggacaagaagaagatcgcttggcctcgcgcgcagatcagttggaagaatttgtccattacgtaaaaggcgagatcaccaaggtagtcggcaaataactgtcagaccaagtttactcatatatactttagattgatttaaaacttcatttttaatttaaaaggatctaggtgaagatcctttttgataatctcatgaccaaaatcccttaacgtgagttttcgttccactgagcgtcagaccccgtagaaaagatcaaaggatcttcttgagatcctttttttctgcgcgtaatctgctgcttgcaaacaaaaaaaccaccgctaccagcggtggtttgtttgccggatcaagagctaccaactctttttccgaaggtaactggcttcagcagagcgcagataccaaatactgtccttctagtgtagccgtagttaggccaccacttcaagaactctgtagcaccgcctacatacctcgctctgctaatcctgttaccagtggctgctgccagtggcgataagtcgtgtcttaccgggttggactcaagacgatagttaccggataaggcgcagcggtcgggctgaacggggggttcgtgcacacagcccagcttggagcgaacgacctacaccgaactgagatacctacagcgtgagctatgagaaagcgccacgcttcccgaagggagaaaggcggacaggtatccggtaagcggcagggtcggaacaggagagcgcacgagggagcttccagggggaaacgcctggtatctttatagtcctgtcgggtttcgccacctctgacttgagcgtcgatttttgtgatgctcgtcaggggggcggagcctatggaaaaacgccagcaacgcggcctttttacggttcctggccttttgctggccttttgctcacatgttctttcctgcgttatcccctgattctgtggataaccgtattaccgcctttgagtgagctgataccgctcgccgcagccgaacgaccgagcgcagcgagtcagtgagcgaggaagcggaagagcgcccaatacgcaaaccgcctctccccgcgcgttggccgattcattaACTACAGGAAACAGCTATGACTCGCAAATGGGCGGTAGGCGTGTATGCCATAGCATTTTTATCCGAATTCGGATCCCTGCAGAAGCTTCTCGAGTCTAGAGATATCCCCGGGaaaNNNNGGTCTCTTACTcaccaactccttcaaacttaattattaacacttccttagttcaatCCATAGAGACC",
            },
        ],
    },
    {
        "file": "one.dna",
        "expected": [
            {
                "node": 1,
                "sequence": "TTACggcctcgtgatacgcctatttttataggttaatgtcatgataataatggtttcttagacgtcaggtggcacttttcggggaaatgtgcgcggaacccctatttgtttatttttctaaatacattcaaatatgtatccgctcatgagacaataaccctgataaatgcttcaataatattgaaaaaggaagagtatgcgctcacgcaactggtccagaaccttgaccgaacgcagcggtggtaacggcgcagtggcggttttcatggcttgttatgactgtttttttggggtacagtctatgcctcgggcatccaagcagcaagcgcgttacgccgtgggtcgatgtttgatgttatggagcagcaacgatgttacgcagcagggcagtcgccctaaaacaaagttaaacatcatgagggaagcggtgatcgccgaagtatcgactcaactatcagaggtagttggcgtcatcgagcgccatctcgaaccgacgttgctggccgtacatttgtacggctccgcagtggatggcggcctgaagccacacagcgatattgatttgctggttacggtgaccgtaaggcttgatgaaacaacgcggcgagctttgatcaacgaccttttggaaacttcggcttcccctggagagagcgagattctccgcgctgtagaagtcaccattgttgtgcacgacgacatcattccgtggcgttatccagctaagcgcgaactgcaatttggagaatggcagcgcaatgacattcttgcaggtatcttcgagccagccacgatcgacattgatctggctatcttgctgacaaaagcaagagaacatagcgttgccttggtaggtccagcggcggaggaactctttgatccggttcctgaacaggatctatttgaggcgctaaatgaaaccttaacgctatggaactcgccgcccgactgggctggcgatgagcgaaatgtagtgcttacgttgtcccgcatttggtacagcgcagtaaccggcaaaatcgcgccgaaggatgtcgctgccgactgggcaatggagcgcctgccggcccagtatcagcccgtcatacttgaagctagacaggcttatcttggacaagaagaagatcgcttggcctcgcgcgcagatcagttggaagaatttgtccattacgtaaaaggcgagatcaccaaggtagtcggcaaataactgtcagaccaagtttactcatatatactttagattgatttaaaacttcatttttaatttaaaaggatctaggtgaagatcctttttgataatctcatgaccaaaatcccttaacgtgagttttcgttccactgagcgtcagaccccgtagaaaagatcaaaggatcttcttgagatcctttttttctgcgcgtaatctgctgcttgcaaacaaaaaaaccaccgctaccagcggtggtttgtttgccggatcaagagctaccaactctttttccgaaggtaactggcttcagcagagcgcagataccaaatactgtccttctagtgtagccgtagttaggccaccacttcaagaactctgtagcaccgcctacatacctcgctctgctaatcctgttaccagtggctgctgccagtggcgataagtcgtgtcttaccgggttggactcaagacgatagttaccggataaggcgcagcggtcgggctgaacggggggttcgtgcacacagcccagcttggagcgaacgacctacaccgaactgagatacctacagcgtgagctatgagaaagcgccacgcttcccgaagggagaaaggcggacaggtatccggtaagcggcagggtcggaacaggagagcgcacgagggagcttccagggggaaacgcctggtatctttatagtcctgtcgggtttcgccacctctgacttgagcgtcgatttttgtgatgctcgtcaggggggcggagcctatggaaaaacgccagcaacgcggcctttttacggttcctggccttttgctggccttttgctcacatgttctttcctgcgttatcccctgattctgtggataaccgtattaccgcctttgagtgagctgataccgctcgccgcagccgaacgaccgagcgcagcgagtcagtgagcgaggaagcggaagagcgcccaatacgcaaaccgcctctccccgcgcgttggccgattcattaACTACAGGAAACAGCTATGACTCGCAAATGGGCGGTAGGCGTGTATGCCATAGCATTTTTATCCGAATTCGGATCCCTGCAGAAGCTTCTCGAGTCTAGAGATATCCCCGGGaaaGGAGggtctcaGGAGGTTATCACACTTGGTAATTTCCCCGCATAGCTGAACATCTATACAACACTCANNNNNGGAGAAACGCGCAACAAATTGTTTCTCATTTtacttgagaccTACTtttGGATCCGAATTCAAGCTTCTGCAGTCTAGACTCGAGCCCGGGGATATCTACAACGTCGTGACTGGGAAAACTCCTTACGGGACTTTCCTACTTCACCAAACGTGGCTTGCCAGCCC",
            },
        ],
    },
    {
        "file": "two.dna",
        "expected": [
            {
                "node": 2,
                "sequence": "TTACggcctcgtgatacgcctatttttataggttaatgtcatgataataatggtttcttagacgtcaggtggcacttttcggggaaatgtgcgcggaacccctatttgtttatttttctaaatacattcaaatatgtatccgctcatgagacaataaccctgataaatgcttcaataatattgaaaaaggaagagtatgcgctcacgcaactggtccagaaccttgaccgaacgcagcggtggtaacggcgcagtggcggttttcatggcttgttatgactgtttttttggggtacagtctatgcctcgggcatccaagcagcaagcgcgttacgccgtgggtcgatgtttgatgttatggagcagcaacgatgttacgcagcagggcagtcgccctaaaacaaagttaaacatcatgagggaagcggtgatcgccgaagtatcgactcaactatcagaggtagttggcgtcatcgagcgccatctcgaaccgacgttgctggccgtacatttgtacggctccgcagtggatggcggcctgaagccacacagcgatattgatttgctggttacggtgaccgtaaggcttgatgaaacaacgcggcgagctttgatcaacgaccttttggaaacttcggcttcccctggagagagcgagattctccgcgctgtagaagtcaccattgttgtgcacgacgacatcattccgtggcgttatccagctaagcgcgaactgcaatttggagaatggcagcgcaatgacattcttgcaggtatcttcgagccagccacgatcgacattgatctggctatcttgctgacaaaagcaagagaacatagcgttgccttggtaggtccagcggcggaggaactctttgatccggttcctgaacaggatctatttgaggcgctaaatgaaaccttaacgctatggaactcgccgcccgactgggctggcgatgagcgaaatgtagtgcttacgttgtcccgcatttggtacagcgcagtaaccggcaaaatcgcgccgaaggatgtcgctgccgactgggcaatggagcgcctgccggcccagtatcagcccgtcatacttgaagctagacaggcttatcttggacaagaagaagatcgcttggcctcgcgcgcagatcagttggaagaatttgtccattacgtaaaaggcgagatcaccaaggtagtcggcaaataactgtcagaccaagtttactcatatatactttagattgatttaaaacttcatttttaatttaaaaggatctaggtgaagatcctttttgataatctcatgaccaaaatcccttaacgtgagttttcgttccactgagcgtcagaccccgtagaaaagatcaaaggatcttcttgagatcctttttttctgcgcgtaatctgctgcttgcaaacaaaaaaaccaccgctaccagcggtggtttgtttgccggatcaagagctaccaactctttttccgaaggtaactggcttcagcagagcgcagataccaaatactgtccttctagtgtagccgtagttaggccaccacttcaagaactctgtagcaccgcctacatacctcgctctgctaatcctgttaccagtggctgctgccagtggcgataagtcgtgtcttaccgggttggactcaagacgatagttaccggataaggcgcagcggtcgggctgaacggggggttcgtgcacacagcccagcttggagcgaacgacctacaccgaactgagatacctacagcgtgagctatgagaaagcgccacgcttcccgaagggagaaaggcggacaggtatccggtaagcggcagggtcggaacaggagagcgcacgagggagcttccagggggaaacgcctggtatctttatagtcctgtcgggtttcgccacctctgacttgagcgtcgatttttgtgatgctcgtcaggggggcggagcctatggaaaaacgccagcaacgcggcctttttacggttcctggccttttgctggccttttgctcacatgttctttcctgcgttatcccctgattctgtggataaccgtattaccgcctttgagtgagctgataccgctcgccgcagccgaacgaccgagcgcagcgagtcagtgagcgaggaagcggaagagcgcccaatacgcaaaccgcctctccccgcgcgttggccgattcattaACTACAGGAAACAGCTATGACTCGCAAATGGGCGGTAGGCGTGTATGCCATAGCATTTTTATCCGAATTCGGATCCCTGCAGAAGCTTCTCGAGTCTAGAGATATCCCCGGGaaaAGGTGGTCTCTTACTacaaactcaaaacacagagaacagagagagagmmagagactccattgttgaagtgtgttcactgaactcctcctcaaacAGAAAAATGAAGAGACCTTCGtttGGATCCGAATTCAAGCTTCTGCAGTCTAGACTCGAGCCCGGGGATATCTACAACGTCGTGACTGGGAAAACTCCTTACGGGACTTTCCTACTTCACCAAACGTGGCTTGCCAGCCC",
            }
        ],
    },
    {
        "file": "four.dna",
        "expected": [
            {
                "node": 6,
                "sequence": "ctagagatatccccgggaaaggagggtctctggagcggtgttctgagaatgggcaagctaatcttcttgatccattgagaacctaattttcattattDttttacctaaacataaaaacacaaaaatataagaaaataaaataaaatccttatctaaattcagaacataaaataaataacatctttcatgttaatattttaaaattcattattttgaagccaaaatgggttaaaatttataacaagtgacttaaaattaaaatttccaaaaataagtagaaaattagataatttaaaaattaccaaactcattttatccttcatgactgttatgtactgatgcagtgtaattacccacattataaatggtaattacaaactagtactaccttataaattaattacccccattctcctatcttacaaataaaattaaaaatacggacaaacatggcagtggtgtggtttcgctttaaaaataaaaatatacaaacatgaaagtgatgtgttttcgttgttatatataataatgctcacgatcgagactcaactaaatgatcacgcaaatgtttttcttaggatgaagcctgttgctaatttcttcatctcaaaatccggtcattacgcaatttatagatttgtcgagattttggcttcttctttaaatttgcgcataaaaacttatcaatgtataccttatggctgcatgaaattacctattcttatggttgcatattaaatgttcatactttttatattattttatttagattaaattgtaattttgatccctatttttaaattaaggcattccattaatggaccatttat",
            },
            {
                "node": 7,
                "sequence": "tccattaatggaccatttatgtgacaaaagattaaataacttaaaaatacaaaaavvtcttagtataaattaaatttaaaatattttatataaagataaaataataaaaccataaaatacttactttatttagttaattttataaatactattttacatgtatcattaattagtccagaattattaatttttttaattataaaaatttataaattgaaataaaatatttaatatttaaatatatttaacatttaattttacatgtacttatttttcttataaaattttattttaaaataaatcaactaaaatttgttgttattttagtataattttaaaaaaatacataaactaatatatagattattttaaaattattttatctaatttatgaaaattaagtagatttaaaataacatttaactaatctaaaatttaaaatttattacttgttataattaaaataaactttttcattatttatatataaaaataaatgtagataattttatcaattacataaaataatttatataactaatttacatattaatttatttaattttcctcatttatataattgatattgaaaaacttatttactaaatattttttatagttaaaataaaaatattaacatgtttttttcctaaaaacattaaatattcaaattttattcatttatttaattaaaataaaggtaatttacatattaaaataaattacataatttgtataatttatatattaataaaaaaatatataaattaatttaaattagtcaaataaaaataaaaatatataaactattcaatatatatatatatatatatatatatatatatatatatatatatatatataatataatgacatacaagaaaattaaaaggatttataaaaaggatttatatattaaatattttttaattcataaatttttataatttaaaaaattaactcatacataaataatatttaaaaaattagttaaaaaaataaatatcttaatagtttgttattttaattttaaataagagattataagtttaattcttattattttttttcataattttaactcttaccaagtatttttttcactttgtttaatctctattctctctctctttatatatatatatatatatatatataataaatttctaatcaactaaatagtgtatattttacatgcagagtacataaaaattaaaattgggtataatagttattgtacgtcatctcactcactcttcctcttagaGTCTATATATATGCAATATCTCTGGaCTCCCTATCACCTTCTCTTCTCTAAGcactttactttttttttcagccccatagagacctacttttggatccgaattcaagct",
            },
        ],
    },
    {
        "file": "five.dna",
        "expected": [
            {
                "node": 1,
                "sequence": "agcGAGCTCtagctagctactgctagctagctagctaWwWagctagctagctgatcgatcgtatatattatatctattcgtagctagtCATATGcgtactac",
            }
        ],
    },
]


for file in files:
    print("testing file", file["file"])
    print("--------------------------------")
    sgff = sgffp.SgffReader.from_file(file["file"])
    for expected in file["expected"]:
        actual = sgff.history.get_sequence_at(expected["node"])
        # print("parsed sequence at history node", expected["node"], ":", actual)
        # print(
        #     "expected sequence at history node",
        #     expected["node"],
        #     ":",
        #     expected["sequence"],
        # )
        print("lengths match", len(actual) == len(expected["sequence"]))
        print("sequences match", expected["sequence"] == actual)
        print()
        print()
